routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Helpers\Convert;
use Illuminate\Support\Facades\Route;



Route::get('/', function(){


    return redirect()->route('admin.login');

});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function (){


    //formulario de login
    Route::get('/', 'AuthController@showLoginForm')->name('login');
    Route::post('login', 'AuthController@login')->name('login.do');



    //rotas protegidas
    Route::group(['middleware' => ['auth'] ], function (){
        Route::get('home', 'AuthController@home')->name('home');
//        Route::get('clientes', 'ClienteController@index')->name('clientes.index');
//
//        Route::get('clientes/criar-novo', 'ClienteController@create')->name('clientes.create');
//        Route::post('clientes/store', 'ClienteController@store')->name('clientes.store');




        Route::resource('clientes', 'ClienteController');
        Route::resource('vendedores', 'VendedorController');
        Route::resource('ponto-vendas', 'PontoVendaController');
        Route::resource('clinicas', 'ClinicaController');
        Route::resource('representantes', 'RepresentanteController');
        Route::resource('pets', 'PetController');

        Route::resource("locais", "LocalController");

        Route::post("save-data", "DadoController@saveData")->name("dados.save");

        Route::post("/locais/alerta", "LocalController@alerta")->name("local.alerta");

        Route::get("/relatorio", "RelatorioController@index")->name("relatorio.index");
        Route::get("/relatorio/show/{local}", "RelatorioController@show")->name("relatorio.show");

    });


    //logout
    Route::get('logout', 'AuthController@logout')->name('logout');



});

app/Pet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pet extends Model
{

    public function dono(){

        return $this->belongsTo(User::class, "cliente", "id");

    }


}

app/Http/Controllers/Admin/PetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Cliente;
use App\Helpers\Convert;
use App\Pet;
use http\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Pet as PetRequest;

class PetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $allPets = Pet::all();


        return view("admin.pets.index", [
            "pets" => $allPets
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $clientes = Cliente::all();


        return view("admin.pets.create", [
            "clientes" => $clientes
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PetRequest $request)
    {


        $pet = new Pet();

        $pet->nome = $request->nome_pet;
        $pet->cliente = $request->dono;
        $pet->idade = $request->idade;
        $pet->data_nascimento = Convert::convertDateToUS($request->data_nascimento_pet);
        $pet->data_aquisicao = Convert::convertDateToUS($request->data_aquisicao_pet);
        $pet->doencas_cronicas = $request->doencas_cronicas_pet;
        $pet->deficiencia = $request->deficiencia_pet;

        $pet->save();

        return redirect()->route("admin.pets.index");


    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PetController.php
<?php

namespace App\Http\Controllers;

use App\Pet;
use Illuminate\Http\Request;

class PetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function show(Pet $pet)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function edit(Pet $pet)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pet $pet)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pet  $pet
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pet $pet)
    {
        //
    }
}

resources/views/admin/pets/create.blade.php
@extends('admin.master.master')

@section('content')



    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-user-plus">Novo Pet</h2>


            @if($errors->all())
                @foreach($errors->all() as $error)

                    @message(['color' => 'red'])
                    <p class="icon-exclamation-circle"> {{$error}} </p>

                    @endmessage

                @endforeach

            @endif


            <div class="dash_content_app_header_actions">

                <nav class="dash_content_app_breadcrumb">


                    <ul>
                        <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.pets.index') }}">Pets</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.pets.create') }}" class="text-orange">Novo Pet</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="dash_content_app_box">
            <div class="nav">
                <ul class="nav_tabs">
                    <li class="nav_tabs_item">
                        <a href="#data" class="nav_tabs_item_link active">Dados Cadastrais</a>
                    </li>


                </ul>

                <form class="app_form" action="{{ route('admin.pets.store') }}" method="post" enctype="multipart/form-data">
                    @csrf

                    <div class="nav_tabs_content">
                        <div id="data">






                            <div class="app_collapse mt-2">
                                <div class="app_collapse_header collapse">
                                    <h3>Pet</h3>
                                    <span class="icon-plus-circle icon-notext"></span>
                                </div>

                                <div class="app_collapse_content d-none">

                                    <div class="label_g2">
                                        <label class="label">
                                            <span class="legend">*Nome:</span>
                                            <input type="text" name="nome_pet" placeholder="Nome do pet"
                                                   value="{{ old('nome_pet') }}"/>
                                        </label>



                                        <label class="label">
                                            <span class="legend">*Raça:</span>
                                            <input type="text" name="raca_pet"
                                                   placeholder="Raça do pet" value="{{ old('raca_pet') }}"/>
                                        </label>
                                    </div>

                                    <div class="label_g2">
                                        <label class="label">
                                            <span class="legend">*Idade:</span>
                                            <input type="text" name="idade"
                                                   placeholder="Idade do Pet" value="{{ old('idade') }}"/>
                                        </label>

                                    </div>


                                    <div class="label_g2">
                                        <label class="label">
                                            <span class="legend">*Dono:</span>
                                            <select name="dono" id="dono">

                                                @if(!empty($clientes))

                                                    @foreach($clientes as $cliente)
                                                        <option value="{{ $cliente->id }}"> {{ $cliente->nome }} </option>

                                                    @endforeach

                                                @endif

                                            </select>

                                        </label>

                                        <label class="label">
                                            <span class="legend">*Data de nascimento:</span>
                                            <input type="text" name="data_nascimento_pet" class="mask-date"
                                                   placeholder="Data de nascimento" value="{{ old('data_nascimento_pet') }}"/>
                                        </label>
                                    </div>


                                    <div class="label_g2">

                                        <label class="label">
                                            <span class="legend">*Data de aquisição:</span>
                                            <input class="mask-date" type="text" name="data_aquisicao_pet" placeholder="Data de aquisição"
                                                   value="{{ old('data_aquisicao_pet') }}"/>
                                        </label>


                                        <label class="label">
                                            <span class="legend">Doenças crônicas:</span>
                                            <input type="text" name="doencas_cronicas_pet" placeholder="Doenças crônicas"
                                                   value="{{ old('doencas_cronicas_pet') }}"/>
                                        </label>


                                    </div>


                                    <div class="label_g2">

                                        <label class="label">
                                            <span class="legend">Deficiência:</span>
                                            <input  type="text" name="deficiencia_pet" placeholder="Deficiência(s)"
                                                   value="{{ old('deficiencia_pet') }}"/>
                                        </label>


                                        <label class="label">
                                            <span class="legend">*Imagem:</span>
                                            <input type="file" name="imagem_pet"
                                                   value="{{ old('imagem_pet') }}"/>
                                        </label>


                                    </div>


                                </div>
                            </div>



                        </div>


                    </div>

                    <div class="text-right mt-2">
                        <button class="btn btn-large btn-green icon-check-square-o" type="submit">Salvar Alterações
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/pets/index.blade.php
@extends('admin.master.master')

@section('content')

    <section class="dash_content_app">




        <header class="dash_content_app_header">
            <h2 class="icon-search">Filtro</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href=" {{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.pets.index') }}" class="text-orange">Pets</a></li>
                    </ul>
                </nav>

                <a href="{{ route('admin.pets.create') }}" class="btn btn-orange icon-user ml-1">Criar Pet</a>
                <button class="btn btn-green icon-search icon-notext ml-1 search_open"></button>
            </div>
        </header>


        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <table id="dataTable" class="nowrap stripe" width="100" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome </th>
                        <th>Dono</th>
                        <th>Raça</th>
                        <th>Idade</th>
                        <th>Ações</th>

                    </tr>
                    </thead>

                    <tbody>

                    @if(isset($pets))

                        @foreach($pets as $pet)


                            <tr>
                                <td> {{$pet->id}} </td>
                                <td> {{$pet->nome}} </td>
                                <td> {{$pet->dono["name"]}} </td>
                                <td> {{$pet->raca}} </td>
                                <td> {{$pet->idade}} </td>

                                <td>
                                    <form method="post" action="{{ route('admin.pets.destroy', ['pet' => $pet->id])  }}" onsubmit="return confirm('Tem certeza que deseja excluir?')">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-red icon-times"></button>

                                    </form>

                                </td>
                            </tr>

                        @endforeach


                    @endif




                    </tbody>


                </table>
            </div>
        </div>
    </section>


@endsection