routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Helpers\Convert;
use Illuminate\Support\Facades\Route;



Route::get('/', function(){


    return redirect()->route('admin.login');

});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function (){


    //formulario de login
    Route::get('/', 'AuthController@showLoginForm')->name('login');
    Route::post('login', 'AuthController@login')->name('login.do');



    //rotas protegidas
    Route::group(['middleware' => ['auth'] ], function (){
        Route::get('home', 'AuthController@home')->name('home');
//        Route::get('clientes', 'ClienteController@index')->name('clientes.index');
//
//        Route::get('clientes/criar-novo', 'ClienteController@create')->name('clientes.create');
//        Route::post('clientes/store', 'ClienteController@store')->name('clientes.store');




        Route::resource('clientes', 'ClienteController');
        Route::resource('vendedores', 'VendedorController');
        Route::resource('ponto-vendas', 'PontoVendaController');
        Route::resource('clinicas', 'ClinicaController');
        Route::resource('representantes', 'RepresentanteController');
        Route::resource('pets', 'PetController');

        Route::resource("locais", "LocalController");

        Route::post("save-data", "DadoController@saveData")->name("dados.save");

        Route::post("/locais/alerta", "LocalController@alerta")->name("local.alerta");

        Route::get("/relatorio", "RelatorioController@index")->name("relatorio.index");
        Route::get("/relatorio/show/{local}", "RelatorioController@show")->name("relatorio.show");

    });


    //logout
    Route::get('logout', 'AuthController@logout')->name('logout');



});

app/Http/Controllers/Admin/RelatorioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dado;
use App\Helpers\Convert;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Local;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use stdClass;

class RelatorioController extends Controller
{


    public function index()
    {

        $locais = Local::all();

        return view("admin.relatorios.index")->with([
            "locais" => $locais
        ]);
    }


    private function isMorning(Carbon $date): bool
    {
        if ($date->hour < 12) {

            return true;
        }

        return false;
    }


    public function show($local)
    {

        $local = Local::find($local);

        $maximumNoisePerLocation = 0;

        /**@var Collection $data */
        $data = $local->data();

        if($local->tipo == "espaco"){
            $maximumNoisePerLocation = 65;

        }else if($local->tipo == "industrial"){
            $maximumNoisePerLocation = 70;

        }
        else if($local->tipo == "escola"){
            $maximumNoisePerLocation = 55;
        }

        $maximumNoisePerLocation = 50;

        $dbs = [];
        $times = [];
        $max = [];

        foreach ($data as $item) {

            $dbs[] = $item->max_db;
            $times[] = "{$item->created_at->hour}:{$item->created_at->minute}:{$item->created_at->second}";
            $max[] = $maximumNoisePerLocation;
        }


        //CHART


        $chartData = new stdClass();
        $chartData->times = implode("','", $times);
        $chartData->times = "'{$chartData->times}'";
        $chartData->dbs = implode(",", $dbs);
        $chartData->standardDeviation =  number_format(Convert::standardDeviation($dbs), 2);
        $chartData->avg = number_format( Convert::getMedia($dbs), 2 );
        $chartData->max = implode(",", $max);



        return view("admin.relatorios.show")->with([
            "local" => $local,
            "data" => $data,
            "chart" => $chartData,
        ]);
    }

}

resources/views/admin/relatorios/index.blade.php
@extends('admin.master.master')

@section('content')

    <section class="dash_content_app">




        <header class="dash_content_app_header">
            <h2 class="icon-search">Filtro</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href=" {{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.locais.index') }}" class="text-orange">Locais</a></li>
                    </ul>
                </nav>

                <a href="{{ route('admin.locais.create') }}" class="btn btn-orange icon-user ml-1">Cadastrar novo local</a>
                <button class="btn btn-green icon-search icon-notext ml-1 search_open"></button>
            </div>
        </header>




        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <table id="dataTable" class="nowrap stripe" width="100" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        <th>Ações</th>

                    </tr>
                    </thead>

                    <tbody>

                    @if(isset($locais))

                        @foreach($locais as $local)

                            <tr>
                                <td> {{$local->id}} </td>
                                <td><a class="text-green" href="{{ route('admin.locais.edit', ['local' => $local->id]) }}"> {{$local->nome}} </a> </td>
                                <td> {{$local->tipo}} </td>
                                <td> {{$local->descricao}} </td>

                                <td>

                                    <a class="btn btn-success" href=" {{ route('admin.relatorio.show', ['local' => $local->id] ) }} ">Ver relatório</a>

                                </td>
                            </tr>

                        @endforeach


                    @endif


                    </tbody>


                </table>
            </div>
        </div>
    </section>


@endsection

resources/views/admin/relatorios/show.blade.php
@extends('admin.master.master')



@section('content')


@section('js')

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.min.js"></script>

<script>

var ctx = document.getElementById('myChart').getContext('2d');



var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [ <?= $chart->times ?> ],
        datasets: [

            {
                label: "Decibéis",
                data: [ <?= $chart->dbs ?> ],
                borderWidth: 2,
                borderColor: 'rgba(77, 176, 253, 0.85)',
                backgroundColor: 'transparent'
            },

            {
                label: "Limiar de ruído para esse tipo de atividade",
                data: [ <?=  $chart->max  ?> ],
                borderWidth: 2,
                borderColor: 'rgba(255, 99, 71, 0.5)',
                backgroundColor: 'transparent'
            },

        ],

    },
    options: {

        plugins: {
            title: {
                display: true,
                text: 'Relatório de ruído - {{ $local->nome }}'
            }
        },

        scales: {
            y: {
                title: {
                    display: true,
                    text: 'Decibéis'
                },
                beginAtZero: true,


            },

            x: {
                title: {
                    display: true,
                    text: 'Tempo'
                },
                beginAtZero: true,


            },




        }
    }
});



</script>


@endsection

<section class="dash_content_app">

    <header class="dash_content_app_header">
        <h2 class="icon-user-plus"> Local: {{ $local->nome }} </h2>


        @if($errors->all())
        @foreach($errors->all() as $error)

        @message(['color' => 'red'])
        <p class="icon-exclamation-circle"> {{$error}} </p>

        @endmessage

        @endforeach

        @endif


        <div class="dash_content_app_header_actions">

            <nav class="dash_content_app_breadcrumb">


                <ul>
                    <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                    <li class="separator icon-angle-right icon-notext"></li>
                    <li><a href="{{ route('admin.relatorio.index') }}"> Relatórios </a></li>
                    <li class="separator icon-angle-right icon-notext"></li>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="dash_content_app_box">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-6">


                    <div class="dash_content_app_box_stage">

                        <table id="dataTable" class="nowrap stripe" width="100" style="width: 100% !important;">

                            <thead>
                                <tr>
                                    <th>Média em DB</th>
                                    <th> Dia/Horário </th>

                                </tr>
                            </thead>

                            <tbody>

                                @if(isset($data))

                                @foreach($data as $dataItem)

                                <tr>

                                    <td> {{$dataItem->avg_db}} </td>
                                    <td> {{ convert_to_date_br($dataItem->created_at) }} </td>

                                </tr>

                                @endforeach


                                @endif

                            </tbody>


                        </table>
                    </div>


                </div>

                <div class="col-md-5 text-center">

                    <h2 class="text-center my-3 badge badge-info"> Desvio padrão: {{ $chart->standardDeviation }} </h2>
                    <h2 class="text-center my-3 badge badge-info"> Média: {{ $chart->avg }} </h2>
                    <canvas id="myChart" width="100" height="100"></canvas>


                </div>



            </div>



        </div>

    </div>
</section>

@endsection




@section('js')




<script>




</script>

@endsection